<%@ Page Title="Exhortations" Language="C#" MasterPageFile="~/Site Masters/Site.Master" AutoEventWireup="true" CodeBehind="Exhortations.aspx.cs" Inherits="XBCAD7319_ChariTech_Website.Pages.Exhortations" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <div class="main-container">
        <!-- Exhortations Section -->
        <div class="section exhortationSelect">
            <div style="text-align: center;">
                <h3>Exhortations </h3>
            </div>
            <div class="exhortations-list">
                <!-- Repeat this block for each exhortation dynamically -->
                <div class="exhortation-item">
                    <div class="exhortation-info">
                        <p class="title">Talk Title | 01-01-2024</p>
                        <p class="description">Brief Talk Description</p>
                    </div>
                    <div class="exhortation-actions">
                        <a href="#" class="details-link">Details ></a>
                        <button class="play-button">▶</button>
                    </div>
                </div>
            </div>
        </div>


        <!-- Temporary list to store exhortations -->
        <div class="section exhortationSelect">
            <div style="text-align: center;">
                <h3>Exhortations</h3>

                
            </div>
            <ListView ID="exhortationListView" class="exhortations-list">
                <ItemTemplate>
                    <div class="exhortation-item">
                        <div class="exhortation-info">
                            <p class="title">
                                <%# Eval("Title") %> | <%# Eval("Date", "{0:dd-MM-yyyy}") %>
                            </p>
                            <p class="description">Speaker: <%# Eval("Speaker") %></p>
                        </div>
                        <div class="exhortation-actions">
                            <a href="#" class="details-link">Details ></a>
                            <button class="play-button" onclick="playAudio('<%# Eval("AudioFilePath") %>')">▶</button>
                        </div>
                    </div>
                </ItemTemplate>
            </ListView>
        </div>

      


              <div class="section exhortationDisplay">
                  <div style="text-align: center;">
                      <h3>*Talk Title* </h3>
                  </div>
                  <h4 class="section-heading">*A brief descriptive summary*</h4>

                  <div class="audio-player">
                      <div class="audio-header">
                          <span class="speaker">Marshal</span>
                          <span class="date">01-01-2024</span>
                      </div>
                      <div class="audio-controls">
                          <button class="play-button2" onclick="togglePlayPause()">▶</button>
                          <div class="progress-container">
                              <div class="exh-progress-bar">
                                  <div class="exh-progress"></div>
                              </div>
                              <div class="timestamps">
                                  <span class="current-time">10:11</span>
                                  <span class="total-time">20:39</span>
                              </div>
                          </div>
                      </div>
                  </div>


                  <h5 class="section-heading"></h5>
                  <h5 class="Section-heading">"This is an Autogenerated transcript, that descripes the words and ideas that were covered in an exhortation..."</h5>

              </div>


    </div >




    <script>
        let audioPlayer = new Audio();
        let isPlaying = false;

        // Function to play selected audio
        function playAudio(audioPath) {
            if (isPlaying) {
                audioPlayer.pause();
                isPlaying = false;
                return;
            }

            audioPlayer.src = audioPath;
            audioPlayer.play();
            isPlaying = true;

            audioPlayer.addEventListener('ended', function () {
                isPlaying = false;
            });
        }

        // Toggle play/pause in the display section
        function togglePlayPause() {
            const playButton = document.querySelector('.play-button2');
            if (isPlaying) {
                audioPlayer.pause();
                playButton.textContent = '▶';
            } else {
                audioPlayer.play();
                playButton.textContent = '❚❚';
            }
            isPlaying = !isPlaying;
        }
    </script>



</asp:Content>


