<%@ Page Title="Exhortations" Language="C#" MasterPageFile="~/Site Masters/Site.Master" AutoEventWireup="true" CodeBehind="Exhortations.aspx.cs" Inherits="XBCAD7319_ChariTech_Website.Pages.Exhortations" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <div class="main-container">
        <!-- Exhortations Section -->
        <div class="section">
            <h3 class="headings">Exhortations</h3>
            <div class="exhortation-list">
                <!-- Dynamic list of Exhortations -->
                <asp:Repeater ID="ExhortationListRepeater" runat="server">
                    <ItemTemplate>
                        <div class="exhortation-item">
                            <div class="exhortation-info">
                                <p><%# Eval("Title") %> | <%# Eval("Date", "{0:MM-dd-yyyy}") %></p>
                                <p>Speaker: <%# Eval("Speaker") %></p>
                            </div>
                            <a class="details-link" href="#">Details ></a>
                            <!-- Play/Pause button -->
                            <button id="playButton_<%# Eval("ExhortationID") %>" class="play-button" onclick="togglePlayPause('<%# Eval("ExhortationID") %>')">▶</button>
                        </div>
                    </ItemTemplate>
                </asp:Repeater>
            </div>
        </div>

       <script type="text/javascript">
           // Global variables to track the currently playing audio and its ID
           var currentAudio = null;
           var currentExhortationId = null;

           // Function to toggle between play and pause
           function togglePlayPause(exhortationId) {
               var playButton = document.getElementById("playButton_" + exhortationId);

               // If the same exhortation is playing, toggle between play and pause
               if (currentExhortationId === exhortationId && currentAudio !== null) {
                   if (currentAudio.paused) {
                       currentAudio.play();
                       playButton.innerHTML = "❚❚";  // Change to pause icon
                   } else {
                       currentAudio.pause();
                       playButton.innerHTML = "▶";  // Change to play icon
                   }
               } else {
                   // Pause any currently playing audio
                   if (currentAudio !== null) {
                       currentAudio.pause();
                       var previousButton = document.getElementById("playButton_" + currentExhortationId);
                       if (previousButton) {
                           previousButton.innerHTML = "▶";  // Reset the previous button to play icon
                       }
                   }

                   // Play the new exhortation
                   currentExhortationId = exhortationId;
                   currentAudio = new Audio("DownloadExhortation.aspx?id=" + exhortationId);

                   // Add an event listener to start playing only when the audio is ready
                   currentAudio.addEventListener('canplaythrough', function () {
                       currentAudio.play();
                       playButton.innerHTML = "❚❚";  // Change to pause icon
                   });

                   // Handle the case when the audio ends
                   currentAudio.onended = function () {
                       playButton.innerHTML = "▶";  // Reset button to play icon when audio ends
                       currentAudio = null;
                       currentExhortationId = null;
                   };
               }
           }
       </script>




        <div class="section exhortationDisplay">
            <div style="text-align: center;">
                <h3>*Talk Title* </h3>
            </div>
            <h4 class="section-heading">*A brief descriptive summary*</h4>

            <div class="audio-player">
                <div class="audio-header">
                    <span class="speaker">Marshal</span>
                    <span class="date">01-01-2024</span>
                </div>
                <div class="audio-controls">
                    <button class="play-button2" onclick="togglePlayPause()">▶</button>
                    <div class="progress-container">
                        <div class="exh-progress-bar">
                            <div class="exh-progress"></div>
                        </div>
                        <div class="timestamps">
                            <span class="current-time">10:11</span>
                            <span class="total-time">20:39</span>
                        </div>
                    </div>
                </div>
            </div>


            <h5 class="section-heading"></h5>
            <h5 class="Section-heading">"This is an Autogenerated transcript, that descripes the words and ideas that were covered in an exhortation..."</h5>

        </div>


    </div>




    <script>
        let audioPlayer = new Audio();
        let isPlaying = false;

        // Function to play selected audio
        function playAudio(audioPath) {
            if (isPlaying) {
                audioPlayer.pause();
                isPlaying = false;
                return;
            }

            audioPlayer.src = audioPath;
            audioPlayer.play();
            isPlaying = true;

            audioPlayer.addEventListener('ended', function () {
                isPlaying = false;
            });
        }

        // Toggle play/pause in the display section
        function togglePlayPause() {
            const playButton = document.querySelector('.play-button2');
            if (isPlaying) {
                audioPlayer.pause();
                playButton.textContent = '▶';
            } else {
                audioPlayer.play();
                playButton.textContent = '❚❚';
            }
            isPlaying = !isPlaying;
        }
    </script>



</asp:Content>


